# Generated by Django 4.2 on 2024-09-10 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, verbose_name='производитель:')),
                ('brand_slug', models.SlugField(max_length=255, verbose_name='слаг:')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True, verbose_name='Название категории:')),
                ('category_slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг категорий')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категорий',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название:')),
                ('price', models.IntegerField(verbose_name='Цена:')),
                ('img1', models.ImageField(upload_to='media', verbose_name='картинка1:')),
                ('img2', models.ImageField(upload_to='media', verbose_name='картинка2:')),
                ('img3', models.ImageField(upload_to='media', verbose_name='картинка3:')),
                ('description', models.TextField(verbose_name='описание:')),
                ('characteristics', models.TextField(verbose_name='характеристики:')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komp_sh.brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komp_sh.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий:')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления:')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komp_sh.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментария',
                'verbose_name_plural': 'Комментарий',
            },
        ),
    ]
